

import { type NextPage } from "next";
import Head from "next/head";
import MainMenu from "~/components/MainMenu";
import { TemplateProps } from "~/interfaces/templateProps";

const Template: NextPage<TemplateProps> = ({ titleHead, children }) => {

    return (
        <>
            <Head>
                <title>{ titleHead }</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div className="flex h-screen overflow-hidden bg-white">
                    <MainMenu />
                    <div className="flex flex-col flex-1 w-0 overflow-hidden">
                        <main className="relative flex-1 overflow-y-auto focus:outline-none">
                            <div className="py-6">
                                { children }
                            </div>
                        </main>
                    </div>
                </div>
            </main>
        </>
    );
};


export default Template;