import { type NextPage } from "next";
import Head from "next/head";
import MainMenu from "~/components/MainMenu";
import { type TemplateProps } from "~/interfaces/templateProps";
import Loader from "./Loader";

/**
 * This is a TypeScript React component that renders a template with a title, meta description,
 * favicon, loader, main menu, and children content.
 * @param  - - `Template`: a functional component that returns a JSX element
 * @returns The `Template` component is being returned, which is a Next.js page component that renders
 * a layout with a header, a main content area, and a sidebar menu. The `titleHead` and `children`
 * props are used to set the page title and render the child components within the main content area.
 */

const Template: NextPage<TemplateProps> = ({ titleHead, children }) => {

    return (
        <>
            <Head>
                <title>{ titleHead }</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Loader />
                <div className="flex h-screen overflow-hidden bg-white">
                    <MainMenu />
                    <div className="flex flex-col flex-1 w-0 overflow-hidden">
                        <main className="relative flex-1 overflow-y-auto focus:outline-none">
                            <div className="py-6">
                                { children }
                            </div>
                        </main>
                    </div>
                </div>
            </main>
        </>
    );
};


export default Template;